### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by davipatricio** [davipatricio/dockerjs#2]
- [ ] Client
  - [ ] Support more ways of connecting to host

- [ ] Containers
  - [x] List containers
  - [x] Create containers
  - [x] Inspect a container
  - [x] List processes running inside a container
  - [ ] Get container logs
  - [ ] Get changes on a container's filesystem
  - [ ] Export a container
  - [ ] Get container stats based on resource usage
  - [ ] Resize a container TTY
  - [x] Start/stop/restart/kill a container
  - [x] Pause/unpause a container
  - [x] Rename a container
  - [ ] Attach to a container via a websocket
  - [ ] Wait for a container
  - [x] Remove a container
  - [ ] Get information about files in a container
  - [ ] Get an archive of a filesystem resource in a container
  - [ ] Extract an archive of files or folders to a directory in a container
  - [x] Delete stopped containers
